import Vue from 'vue';
import AutoComplete from 'iview/src/components/auto-complete';
import Badge from 'iview/src/components/badge';
import Button from 'iview/src/components/button';
import Carousel from 'iview/src/components/carousel';
import Checkbox from 'iview/src/components/checkbox';
import ColorPicker from 'iview/src/components/color-picker';
import Collapse from 'iview/src/components/collapse';
import Panel from 'iview/src/components/panel';
import DatePicker from 'iview/src/components/date-picker';
import Form from 'iview/src/components/form';
import Icon from 'iview/src/components/icon';
import Input from 'iview/src/components/input';
import InputNumber from 'iview/src/components/input-number';
import Message from 'iview/src/components/message';
import Modal from 'iview/src/components/modal';
import Page from 'iview/src/components/page';
import Poptip from 'iview/src/components/poptip';
import Radio from 'iview/src/components/radio';
import Spin from 'iview/src/components/spin';
import Switch from 'iview/src/components/switch';
import Table from 'iview/src/components/table';
import Tabs from 'iview/src/components/tabs';
import Tooltip from 'iview/src/components/tooltip';
import Alert from 'iview/src/components/alert';
import { Row, Col } from 'iview/src/components/grid';
import { Select, Option } from 'iview/src/components/select';
import locale from 'iview/src/components/locale';
import lang from 'iview/dist/locale/en-US';

locale(lang);

Vue.prototype.$IVIEW = {};
Vue.prototype.$Message = Message;
Vue.prototype.$Modal = Modal;

Vue.component('Button', Button);
Vue.component('Table', Table);
Vue.component('Icon', Icon);
Vue.component('AutoComplete', AutoComplete);
Vue.component('Poptip', Poptip);
Vue.component('Modal', Modal);
Vue.component('Row', Row);
Vue.component('Col', Col);
Vue.component('Select', Select);
Vue.component('Option', Option);
Vue.component('Input', Input);
Vue.component('Form', Form);
Vue.component('FormItem', Form.Item);
Vue.component('DatePicker', DatePicker);
Vue.component('ColorPicker', ColorPicker);
Vue.component('Radio', Radio);
Vue.component('RadioGroup', Radio.Group);
Vue.component('Tooltip', Tooltip);
Vue.component('Tabs', Tabs);
Vue.component('TabPane', Tabs.Pane);
Vue.component('Carousel', Carousel);
Vue.component('CarouselItem', Carousel.Item);
Vue.component('Checkbox', Checkbox);
Vue.component('Badge', Badge);
Vue.component('Spin', Spin);
Vue.component('Page', Page);
Vue.component('InputNumber', InputNumber);
Vue.component('ISwitch', Switch);
Vue.component('Alert', Alert);
Vue.component('Collapse', Collapse);
Vue.component('Panel', Panel);
